//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Errors
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class Error500ResponseBodyPayload
    {
        [JsonProperty("error")]
        public Error500ResponseBodyError Error { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Internal Server Error - An unexpected server error occurred
    /// </summary>
    public class Error500ResponseBody : MeitnerException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public Error500ResponseBodyPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error500ResponseBody.Payload.Error instead.")]
        public Error500ResponseBodyError Error { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error500ResponseBody.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        private static string ErrorMessage(Error500ResponseBodyPayload payload, string body)
        {
            string? message = payload.Error?.Message;
            if (!string.IsNullOrEmpty(message))
            {
                return message;
            }

            return "API error occurred";
        }

        public Error500ResponseBody(
            Error500ResponseBodyPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base(ErrorMessage(payload, body), request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Error = payload.Error;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }

}