//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner
{
    using Meitner.Hooks;
    using Meitner.Models.Components;
    using Meitner.Models.Errors;
    using Meitner.Utils;
    using Meitner.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Directory API: Generated API documentation
    /// </summary>
    public interface IMeitnerSDK
    {
        public ISchools Schools { get; }
        public IGroups Groups { get; }
        public IEmployees Employees { get; }
        public IEmployeePlacements EmployeePlacements { get; }
        public IGuardians Guardians { get; }
        public IStudents Students { get; }
        public IStudentPlacements StudentPlacements { get; }
        public IAuditEvents AuditEvents { get; }
    }


    /// <summary>
    /// Directory API: Generated API documentation
    /// </summary>
    public class MeitnerSDK: IMeitnerSDK
    {
        public SDKConfig SDKConfiguration { get; private set; }

        private const string _language = "csharp";
        private const string _sdkVersion = "0.0.1";
        private const string _sdkGenVersion = "2.721.0";
        private const string _openapiDocVersion = "v1";
        public ISchools Schools { get; private set; }
        public IGroups Groups { get; private set; }
        public IEmployees Employees { get; private set; }
        public IEmployeePlacements EmployeePlacements { get; private set; }
        public IGuardians Guardians { get; private set; }
        public IStudents Students { get; private set; }
        public IStudentPlacements StudentPlacements { get; private set; }
        public IAuditEvents AuditEvents { get; private set; }

        public MeitnerSDK(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Schools = new Schools(SDKConfiguration);

            Groups = new Groups(SDKConfiguration);

            Employees = new Employees(SDKConfiguration);

            EmployeePlacements = new EmployeePlacements(SDKConfiguration);

            Guardians = new Guardians(SDKConfiguration);

            Students = new Students(SDKConfiguration);

            StudentPlacements = new StudentPlacements(SDKConfiguration);

            AuditEvents = new AuditEvents(SDKConfiguration);
        }

        public MeitnerSDK(Meitner.Models.Components.Security? security = null, Func<Meitner.Models.Components.Security>? securitySource = null, SDKConfig.Server? server = null, string? serverUrl = null, Dictionary<string, string>? urlParams = null, IMeitnerHttpClient? client = null, RetryConfig? retryConfig = null)
        {

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Meitner.Models.Components.Security>? _securitySource = null;

            if(securitySource != null)
            {
                _securitySource = securitySource;
            }
            else if(security != null)
            {
                _securitySource = () => security;
            }
            else
            {
                throw new Exception("security and securitySource cannot both be null");
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ServerName = server,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Schools = new Schools(SDKConfiguration);

            Groups = new Groups(SDKConfiguration);

            Employees = new Employees(SDKConfiguration);

            EmployeePlacements = new EmployeePlacements(SDKConfiguration);

            Guardians = new Guardians(SDKConfiguration);

            Students = new Students(SDKConfiguration);

            StudentPlacements = new StudentPlacements(SDKConfiguration);

            AuditEvents = new AuditEvents(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new MeitnerHttpClient());

            public SDKBuilder() { }

            public SDKBuilder WithServer(SDKConfig.Server server)
            {
                _sdkConfig.ServerName = server;
                return this;
            }

            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            public SDKBuilder WithSecuritySource(Func<Meitner.Models.Components.Security> securitySource)
            {
                _sdkConfig.SecuritySource = securitySource;
                return this;
            }

            public SDKBuilder WithSecurity(Meitner.Models.Components.Security security)
            {
                _sdkConfig.SecuritySource = () => security;
                return this;
            }

            public SDKBuilder WithClient(IMeitnerHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            public MeitnerSDK Build()
            {
              if (_sdkConfig.SecuritySource == null) {
                  throw new Exception("securitySource cannot be null. One of `Security` or `securitySource` needs to be defined.");
              }
              return new MeitnerSDK(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}