//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner
{
    using Meitner.Hooks;
    using Meitner.Models.Components;
    using Meitner.Models.Errors;
    using Meitner.Utils;
    using Meitner.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    /// <summary>
    /// Directory API: Generated API documentation.
    /// </summary>
    public interface IMeitnerSDK
    {
        public ISchools Schools { get; }

        public IGroups Groups { get; }

        public IEmployees Employees { get; }

        public IEmployeePlacements EmployeePlacements { get; }

        public IGuardians Guardians { get; }

        public IStudents Students { get; }

        public IStudentPlacements StudentPlacements { get; }

        public IAuditEvents AuditEvents { get; }
    }

    /// <summary>
    /// Directory API: Generated API documentation.
    /// </summary>
    public class MeitnerSDK: IMeitnerSDK
    {
        /// <summary>
        /// The main SDK Configuration.
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }
        /// <summary>
        /// The Schools sub-SDK.
        /// </summary>
        public ISchools Schools { get; private set; }
        /// <summary>
        /// The Groups sub-SDK.
        /// </summary>
        public IGroups Groups { get; private set; }
        /// <summary>
        /// The Employees sub-SDK.
        /// </summary>
        public IEmployees Employees { get; private set; }
        /// <summary>
        /// The EmployeePlacements sub-SDK.
        /// </summary>
        public IEmployeePlacements EmployeePlacements { get; private set; }
        /// <summary>
        /// The Guardians sub-SDK.
        /// </summary>
        public IGuardians Guardians { get; private set; }
        /// <summary>
        /// The Students sub-SDK.
        /// </summary>
        public IStudents Students { get; private set; }
        /// <summary>
        /// The StudentPlacements sub-SDK.
        /// </summary>
        public IStudentPlacements StudentPlacements { get; private set; }
        /// <summary>
        /// The AuditEvents sub-SDK.
        /// </summary>
        public IAuditEvents AuditEvents { get; private set; }

        /// <summary>
        /// Initializes a new instance of the SDK based on a <see cref="SDKConfig"/> configuration object.
        /// </summary>
        /// <param name="config">The SDK configuration object.</param>
        public MeitnerSDK(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Schools = new Schools(SDKConfiguration);

            Groups = new Groups(SDKConfiguration);

            Employees = new Employees(SDKConfiguration);

            EmployeePlacements = new EmployeePlacements(SDKConfiguration);

            Guardians = new Guardians(SDKConfiguration);

            Students = new Students(SDKConfiguration);

            StudentPlacements = new StudentPlacements(SDKConfiguration);

            AuditEvents = new AuditEvents(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="security">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="securitySource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="server">The server to use from the predefined server list.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default MeitnerHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        /// <exception cref="ArgumentException">None of <paramref name="security"/> and <paramref name="securitySource"/> were provided.</exception>
        public MeitnerSDK(
            Meitner.Models.Components.Security? security = null,
            Func<Meitner.Models.Components.Security>? securitySource = null,
            SDKConfig.Server? server = null,
            string? serverUrl = null,
            Dictionary<string, string>? urlParams = null,
            IMeitnerHttpClient? client = null,
            RetryConfig? retryConfig = null
        )
        {

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Meitner.Models.Components.Security>? _securitySource = null;

            if(securitySource != null)
            {
                _securitySource = securitySource;
            }
            else if(security != null)
            {
                _securitySource = () => security;
            }
            else
            {
                throw new ArgumentException("security and securitySource cannot both be null");
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ServerName = server,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Schools = new Schools(SDKConfiguration);

            Groups = new Groups(SDKConfiguration);

            Employees = new Employees(SDKConfiguration);

            EmployeePlacements = new EmployeePlacements(SDKConfiguration);

            Guardians = new Guardians(SDKConfiguration);

            Students = new Students(SDKConfiguration);

            StudentPlacements = new StudentPlacements(SDKConfiguration);

            AuditEvents = new AuditEvents(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        /// <summary>
        /// Builder class for constructing an instance of the SDK.
        /// </summary>
        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new MeitnerHttpClient());

            public SDKBuilder() { }

            /// <summary>
            /// Overrides the default server by name.
            /// </summary>
            public SDKBuilder WithServer(SDKConfig.Server server)
            {
                _sdkConfig.ServerName = server;
                return this;
            }

            /// <summary>
            /// Overrides the default server URL for the SDK.
            /// </summary>
            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            /// <summary>
            /// Sets the securitySource security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithSecuritySource(Func<Meitner.Models.Components.Security> securitySource)
            {
                _sdkConfig.SecuritySource = securitySource;
                return this;
            }

            /// <summary>
            /// Sets the security security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithSecurity(Meitner.Models.Components.Security security)
            {
                _sdkConfig.SecuritySource = () => security;
                return this;
            }

            /// <summary>
            /// Sets a custom HTTP client to be used by the SDK.
            /// </summary>
            public SDKBuilder WithClient(IMeitnerHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            /// <summary>
            /// Sets the retry configuration for the SDK.
            /// </summary>
            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            /// <summary>
            /// Builds and returns the SDK instance.
            /// </summary>
            public MeitnerSDK Build()
            {
              if (_sdkConfig.SecuritySource == null) {
                  throw new ArgumentException("securitySource cannot be null. One of `Security` or `securitySource` needs to be defined.");
              }
              return new MeitnerSDK(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}