//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner
{
    using Meitner.Hooks;
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Meitner.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Main configuration for the SDK.
    /// </summary>
    public struct SDKConfig
    {
        /// <summary>
        /// Server identifiers available to the SDK.
        /// </summary>
        public enum Server {
            Production,
            Staging,
        }

        /// <summary>
        /// Server URLs available to the SDK.
        /// </summary>
        public static readonly Dictionary<Server, string> ServerMap = new Dictionary<Server, string>()
        {
            { Server.Production, "https://api.meitner.se/directory/v1" },
            { Server.Staging, "https://api.staging.meitner.se/directory/v1" },
        };

        public IMeitnerHttpClient Client;
        public string ServerUrl;
        public Server? ServerName;
        public string UserAgent;
        public Func<Meitner.Models.Components.Security>? SecuritySource;
        public SDKHooks Hooks;
        public RetryConfig? RetryConfig;

        /// <summary>
        /// Initializes a new instance of the SDKConfig struct with default values.
        /// </summary>
        public SDKConfig(IMeitnerHttpClient? client = null)
        {
            Client = client ?? new MeitnerHttpClient();
            ServerUrl = "";
            ServerName = null;
            UserAgent = "speakeasy-sdk/csharp 0.3.0 2.799.0 v1 Meitner";
            SecuritySource = null;
            Hooks = new SDKHooks();
            RetryConfig = null;
        }

        public string GetTemplatedServerUrl()
        {
            if (!String.IsNullOrEmpty(this.ServerUrl))
            {
                return Utilities.TemplateUrl(Utilities.RemoveSuffix(this.ServerUrl, "/"), new Dictionary<string, string>());
            }
            if (this.ServerName is null)
            {
                this.ServerName = SDKConfig.Server.Production;
            }
            else if (!SDKConfig.ServerMap.ContainsKey(this.ServerName.Value))
            {
                throw new Exception($"Invalid server \"{this.ServerName.Value}\"");
            }

            Dictionary<string, string> serverDefault = new Dictionary<string, string>();

            return Utilities.TemplateUrl(SDKConfig.ServerMap[this.ServerName.Value], serverDefault);
        }
    }
}
