//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// AuditEvent holds the information about an audit event.
    /// </summary>
    public class AuditEvent
    {

        /// <summary>
        /// Unique identifier for the AuditEvent
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Metadata information for the AuditEvent
        /// </summary>
        [JsonProperty("meta")]
        public AuditEventMeta? Meta { get; set; }

        /// <summary>
        /// The timestamp of the event
        /// </summary>
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; } = default!;

        /// <summary>
        /// The type of resource the event occured for
        /// </summary>
        [JsonProperty("resource")]
        public AuditEventResource1 Resource { get; set; } = default!;

        /// <summary>
        /// The ID of the resource the event belongs to
        /// </summary>
        [JsonProperty("resourceID")]
        public string ResourceID { get; set; } = default!;

        /// <summary>
        /// The type of the audit event
        /// </summary>
        [JsonProperty("type")]
        public AuditEventTypeDelete Type { get; set; } = default!;
    }
}