//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Smaller than filters for AuditEvent.
    /// </summary>
    public class AuditEventSearchSmallerThan
    {
        /// <summary>
        /// Metadata information for the AuditEvent.
        /// </summary>
        [JsonProperty("meta")]
        public AuditEventSearchSmallerThanMeta? Meta { get; set; } = null;

        /// <summary>
        /// The timestamp of the event.
        /// </summary>
        [JsonProperty("timestamp")]
        public DateTime? Timestamp { get; set; } = null;
    }
}