//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Pagination information
    /// </summary>
    public class AuditEventSearchPagination
    {

        /// <summary>
        /// Number of items to skip from the beginning of the result set
        /// </summary>
        [JsonProperty("offset")]
        public long Offset { get; set; } = default!;

        /// <summary>
        /// Maximum number of items to return in the result set
        /// </summary>
        [JsonProperty("limit")]
        public long Limit { get; set; } = default!;

        /// <summary>
        /// Total number of items available for pagination
        /// </summary>
        [JsonProperty("total")]
        public long Total { get; set; } = default!;
    }
}