//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Metadata information for the AuditEvent.
    /// </summary>
    public class AuditEventFilterSmallerOrEqualMeta
    {
        /// <summary>
        /// Timestamp when the resource was created.
        /// </summary>
        [JsonProperty("createdAt")]
        public DateTime? CreatedAt { get; set; } = null;

        /// <summary>
        /// Timestamp when the resource was last updated.
        /// </summary>
        [JsonProperty("updatedAt")]
        public DateTime? UpdatedAt { get; set; } = null;
    }
}