//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Not null filters for AuditEvent
    /// </summary>
    public class AuditEventFilterNotNull
    {

        /// <summary>
        /// Metadata information for the AuditEvent
        /// </summary>
        [JsonProperty("meta")]
        public AuditEventFilterNotNullMeta? Meta { get; set; } = null;
    }
}