//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The type of resource the event occured for.
    /// </summary>
    public enum AuditEventResource1
    {
        [JsonProperty("Group")]
        Group,
        [JsonProperty("Guardian")]
        Guardian,
        [JsonProperty("Employee")]
        Employee,
        [JsonProperty("EmployeePlacement")]
        EmployeePlacement,
        [JsonProperty("Student")]
        Student,
        [JsonProperty("StudentPlacement")]
        StudentPlacement,
    }

    public static class AuditEventResource1Extension
    {
        public static string Value(this AuditEventResource1 value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuditEventResource1 ToEnum(this string value)
        {
            foreach(var field in typeof(AuditEventResource1).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuditEventResource1)
                    {
                        return (AuditEventResource1)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuditEventResource1");
        }
    }
}