//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The type of the audit event.
    /// </summary>
    public enum AuditEventFilterEqualsType
    {
        [JsonProperty("Delete")]
        Delete,
    }

    public static class AuditEventFilterEqualsTypeExtension
    {
        public static string Value(this AuditEventFilterEqualsType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuditEventFilterEqualsType ToEnum(this string value)
        {
            foreach(var field in typeof(AuditEventFilterEqualsType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuditEventFilterEqualsType)
                    {
                        return (AuditEventFilterEqualsType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuditEventFilterEqualsType");
        }
    }
}