//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Contains filters for AuditEvent
    /// </summary>
    public class AuditEventSearchContains
    {

        /// <summary>
        /// Unique identifier for the AuditEvent
        /// </summary>
        [JsonProperty("id")]
        public List<string>? Id { get; set; }

        /// <summary>
        /// Metadata information for the AuditEvent
        /// </summary>
        [JsonProperty("meta")]
        public AuditEventSearchContainsMeta? Meta { get; set; } = null;

        /// <summary>
        /// The type of resource the event occured for
        /// </summary>
        [JsonProperty("resource")]
        public List<AuditEventResource>? Resource { get; set; }

        /// <summary>
        /// The ID of the resource the event belongs to
        /// </summary>
        [JsonProperty("resourceID")]
        public List<string>? ResourceID { get; set; }

        /// <summary>
        /// The type of the audit event
        /// </summary>
        [JsonProperty("type")]
        public List<AuditEventType>? Type { get; set; }
    }
}