//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// NOT LIKE filters for Employee
    /// </summary>
    public class EmployeeSearchNotLike
    {

        /// <summary>
        /// Metadata information for the Employee
        /// </summary>
        [JsonProperty("meta")]
        public EmployeeSearchNotLikeMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeeSearchNotLikeExternal? External { get; set; } = null;

        /// <summary>
        /// The identity number of the employee, must be unique within the organization.
        /// </summary>
        [JsonProperty("identityNumber")]
        public string? IdentityNumber { get; set; } = null;

        /// <summary>
        /// The first name of the employee
        /// </summary>
        [JsonProperty("firstName")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// The last name of the employee
        /// </summary>
        [JsonProperty("lastName")]
        public string? LastName { get; set; } = null;

        /// <summary>
        /// The address of the employee
        /// </summary>
        [JsonProperty("address")]
        public EmployeeSearchNotLikeAddress? Address { get; set; } = null;

        /// <summary>
        /// The primary email address of the employee, will be used for communication with the employee from the system and must be unique within the organization.<br/>
        /// 
        /// <remarks>
        /// Can be used to login to the system if password-authentication is enabled for the organization.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("emailAddress1")]
        public string? EmailAddress1 { get; set; } = null;

        /// <summary>
        /// The secondary email address of the employee, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("emailAddress2")]
        public string? EmailAddress2 { get; set; } = null;

        /// <summary>
        /// The primary phone number of the employee, will be used for communication with the employee from the system and must be unique within the organization.
        /// </summary>
        [JsonProperty("phoneNumber1")]
        public string? PhoneNumber1 { get; set; } = null;

        /// <summary>
        /// The secondary phone number of the employee, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("phoneNumber2")]
        public string? PhoneNumber2 { get; set; } = null;
    }
}