//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Filter object for Employee
    /// </summary>
    public class EmployeeFilter
    {

        /// <summary>
        /// Equality filters for Employee
        /// </summary>
        [JsonProperty("equals")]
        public EmployeeFilterEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for Employee
        /// </summary>
        [JsonProperty("notEquals")]
        public EmployeeFilterNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for Employee
        /// </summary>
        [JsonProperty("greaterThan")]
        public EmployeeFilterGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for Employee
        /// </summary>
        [JsonProperty("smallerThan")]
        public EmployeeFilterSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for Employee
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public EmployeeFilterGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for Employee
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public EmployeeFilterSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for Employee
        /// </summary>
        [JsonProperty("contains")]
        public EmployeeFilterContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for Employee
        /// </summary>
        [JsonProperty("notContains")]
        public EmployeeFilterNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for Employee
        /// </summary>
        [JsonProperty("like")]
        public EmployeeFilterLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for Employee
        /// </summary>
        [JsonProperty("notLike")]
        public EmployeeFilterNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for Employee
        /// </summary>
        [JsonProperty("null")]
        public EmployeeFilterNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for Employee
        /// </summary>
        [JsonProperty("notNull")]
        public EmployeeFilterNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the Employee, useful for more complex filters
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<EmployeeFilter>? NestedFilters { get; set; }
    }
}