//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Not contains filters for EmployeePlacement.
    /// </summary>
    public class EmployeePlacementSearchNotContains
    {
        /// <summary>
        /// Unique identifier for the EmployeePlacement.
        /// </summary>
        [JsonProperty("id")]
        public List<string>? Id { get; set; }

        /// <summary>
        /// Metadata information for the EmployeePlacement.
        /// </summary>
        [JsonProperty("meta")]
        public EmployeePlacementSearchNotContainsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the guardian from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeePlacementSearchNotContainsExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the employee the placement belongs to.
        /// </summary>
        [JsonProperty("employeeID")]
        public List<string>? EmployeeID { get; set; }

        /// <summary>
        /// The ID of the school the placement belongs to.
        /// </summary>
        [JsonProperty("schoolID")]
        public List<string>? SchoolID { get; set; }

        /// <summary>
        /// The signature of the employee.
        /// </summary>
        [JsonProperty("signature")]
        public List<string>? Signature { get; set; }

        /// <summary>
        /// The title of the employee.
        /// </summary>
        [JsonProperty("title")]
        public List<string>? Title { get; set; }

        /// <summary>
        /// The roles of the employee.
        /// </summary>
        [JsonProperty("roles")]
        public List<EmployeePlacementRole>? Roles { get; set; }

        /// <summary>
        /// The start date of the placement for the employee.
        /// </summary>
        [JsonProperty("startDate")]
        public List<DateOnly>? StartDate { get; set; }

        /// <summary>
        /// The end date of the placement for the employee.
        /// </summary>
        [JsonProperty("endDate")]
        public List<DateOnly>? EndDate { get; set; }

        /// <summary>
        /// The year the placement was archived for the employee, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public List<string>? ArchiveYear { get; set; }
    }
}