//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Greater than filters for EmployeePlacement
    /// </summary>
    public class EmployeePlacementFilterGreaterThan
    {

        /// <summary>
        /// Metadata information for the EmployeePlacement
        /// </summary>
        [JsonProperty("meta")]
        public EmployeePlacementFilterGreaterThanMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the guardian from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeePlacementFilterGreaterThanExternal? External { get; set; } = null;

        /// <summary>
        /// The start date of the placement for the employee
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly? StartDate { get; set; } = null;

        /// <summary>
        /// The end date of the placement for the employee
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;

        /// <summary>
        /// The timestamp the placement was archived for the employee
        /// </summary>
        [JsonProperty("archivedAt")]
        public DateTime? ArchivedAt { get; set; } = null;
    }
}