//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The address of the employee
    /// </summary>
    public class EmployeeFilterEqualsAddress
    {

        /// <summary>
        /// The postal address of the address
        /// </summary>
        [JsonProperty("postalAddress")]
        public string? PostalAddress { get; set; } = null;

        /// <summary>
        /// The postal code of the address
        /// </summary>
        [JsonProperty("postalCode")]
        public string? PostalCode { get; set; } = null;

        /// <summary>
        /// The city of the address
        /// </summary>
        [JsonProperty("postalCity")]
        public string? PostalCity { get; set; } = null;

        /// <summary>
        /// The country code of the address
        /// </summary>
        [JsonProperty("countryCode")]
        public string? CountryCode { get; set; } = null;

        /// <summary>
        /// The municipality code of the address
        /// </summary>
        [JsonProperty("municipalityCode")]
        public string? MunicipalityCode { get; set; } = null;
    }
}