//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Equality filters for EmployeePlacement.
    /// </summary>
    public class EmployeePlacementFilterEquals
    {
        /// <summary>
        /// Unique identifier for the EmployeePlacement.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Metadata information for the EmployeePlacement.
        /// </summary>
        [JsonProperty("meta")]
        public EmployeePlacementFilterEqualsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the guardian from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeePlacementFilterEqualsExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the employee the placement belongs to.
        /// </summary>
        [JsonProperty("employeeID")]
        public string? EmployeeID { get; set; } = null;

        /// <summary>
        /// The ID of the school the placement belongs to.
        /// </summary>
        [JsonProperty("schoolID")]
        public string? SchoolID { get; set; } = null;

        /// <summary>
        /// The signature of the employee.
        /// </summary>
        [JsonProperty("signature")]
        public string? Signature { get; set; } = null;

        /// <summary>
        /// The title of the employee.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The roles of the employee.
        /// </summary>
        [JsonProperty("roles")]
        public EmployeePlacementFilterEqualsRoles? Roles { get; set; } = null;

        /// <summary>
        /// The start date of the placement for the employee.
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly? StartDate { get; set; } = null;

        /// <summary>
        /// The end date of the placement for the employee.
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the employee, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public string? ArchiveYear { get; set; } = null;

        /// <summary>
        /// The timestamp the placement was archived for the employee.
        /// </summary>
        [JsonProperty("archivedAt")]
        public DateTime? ArchivedAt { get; set; } = null;

        /// <summary>
        /// The percentage of employment for the employee at this school, represented as an integer (e.g., 100 for 100%, 50 for 50%).
        /// </summary>
        [JsonProperty("employmentPercent")]
        public long? EmploymentPercent { get; set; } = null;
    }
}