//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Null filters for EmployeePlacement.
    /// </summary>
    public class EmployeePlacementSearchNull
    {
        /// <summary>
        /// Metadata information for the EmployeePlacement.
        /// </summary>
        [JsonProperty("meta")]
        public EmployeePlacementSearchNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the guardian from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeePlacementSearchNullExternal? External { get; set; } = null;

        /// <summary>
        /// The signature of the employee.
        /// </summary>
        [JsonProperty("signature")]
        public bool? Signature { get; set; } = null;

        /// <summary>
        /// The title of the employee.
        /// </summary>
        [JsonProperty("title")]
        public bool? Title { get; set; } = null;

        /// <summary>
        /// The roles of the employee.
        /// </summary>
        [JsonProperty("roles")]
        public bool? Roles { get; set; } = null;

        /// <summary>
        /// The end date of the placement for the employee.
        /// </summary>
        [JsonProperty("endDate")]
        public bool? EndDate { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the employee, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public bool? ArchiveYear { get; set; } = null;

        /// <summary>
        /// The timestamp the placement was archived for the employee.
        /// </summary>
        [JsonProperty("archivedAt")]
        public bool? ArchivedAt { get; set; } = null;
    }
}