//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Greater than or equal filters for Employee.
    /// </summary>
    public class EmployeeSearchGreaterOrEqual
    {
        /// <summary>
        /// Metadata information for the Employee.
        /// </summary>
        [JsonProperty("meta")]
        public EmployeeSearchGreaterOrEqualMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public EmployeeSearchGreaterOrEqualExternal? External { get; set; } = null;

        /// <summary>
        /// The date of birth of the employee.
        /// </summary>
        [JsonProperty("dateOfBirth")]
        public DateOnly? DateOfBirth { get; set; } = null;

        /// <summary>
        /// The address of the employee.
        /// </summary>
        [JsonProperty("address")]
        public EmployeeSearchGreaterOrEqualAddress? Address { get; set; } = null;
    }
}