//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// GradeUpperSecondary represents a grade awarded to a student in upper secondary school (Swedish: gymnasieskola).<br/>
    /// Grades are scoped to the organization of the API key used. The CourseCode field uses the national course code as defined by the Swedish school authorities (e.g. "MATMAT01a").
    /// </summary>
    public class GradeUpperSecondary
    {
        /// <summary>
        /// Unique identifier for the GradeUpperSecondary.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Metadata information for the GradeUpperSecondary.
        /// </summary>
        [JsonProperty("meta")]
        public GradeUpperSecondaryMeta? Meta { get; set; }

        /// <summary>
        /// External is a reusable object that can be used to store external information about the grade from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GradeUpperSecondaryExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("studentID")]
        public string StudentID { get; set; } = default!;

        /// <summary>
        /// The ID of the school where the student received the grade. Must reference a school within the organization.
        /// </summary>
        [JsonProperty("schoolID")]
        public string SchoolID { get; set; } = default!;

        /// <summary>
        /// The national course code as defined by the Swedish school authorities (e.g. "MATMAT01a" for Mathematics 1a).
        /// </summary>
        [JsonProperty("courseCode")]
        public string CourseCode { get; set; } = default!;

        /// <summary>
        /// The language code for the grade, used when the course is taught in a specific language.
        /// </summary>
        [JsonProperty("languageCode")]
        public string? LanguageCode { get; set; } = null;

        /// <summary>
        /// The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher1EmployeeID")]
        public string? Teacher1EmployeeID { get; set; } = null;

        /// <summary>
        /// The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher2EmployeeID")]
        public string? Teacher2EmployeeID { get; set; } = null;

        /// <summary>
        /// The grade awarded to the student.
        /// </summary>
        [JsonProperty("grade")]
        public GradeUpperSecondaryGrade? Grade { get; set; } = null;

        /// <summary>
        /// The date the grade was awarded.
        /// </summary>
        [JsonProperty("gradeDate")]
        public DateOnly? GradeDate { get; set; } = null;

        /// <summary>
        /// A comment about the grade from the teacher.
        /// </summary>
        [JsonProperty("gradeComment")]
        public string? GradeComment { get; set; } = null;

        /// <summary>
        /// The extent of the course for this student.
        /// </summary>
        [JsonProperty("extent")]
        public GradeUpperSecondaryExtent? Extent { get; set; } = null;

        /// <summary>
        /// The school year of the student at the time the grade was awarded.
        /// </summary>
        [JsonProperty("schoolYear")]
        public GradeUpperSecondarySchoolYear? SchoolYear { get; set; } = null;

        /// <summary>
        /// The section/type of the course in the student's study plan.
        /// </summary>
        [JsonProperty("section")]
        public GradeUpperSecondarySection? Section { get; set; } = null;

        /// <summary>
        /// A comment from the teacher about the student's performance.
        /// </summary>
        [JsonProperty("teacherComment")]
        public string? TeacherComment { get; set; } = null;

        /// <summary>
        /// Whether this course grade should be included when calculating the student's final grade certificate.
        /// </summary>
        [JsonProperty("includeOnFinalGrade")]
        public bool IncludeOnFinalGrade { get; set; } = default!;

        /// <summary>
        /// The title of the program this course belongs to. Used to associate the course with a specific educational program.
        /// </summary>
        [JsonProperty("programTitle")]
        public string? ProgramTitle { get; set; } = null;

        /// <summary>
        /// The date the student started the course.
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly? StartDate { get; set; } = null;

        /// <summary>
        /// The date the student finished the course.
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;
    }
}