//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The section/type of the course in the student's study plan.
    /// </summary>
    public enum GradeUpperSecondaryUpdateSection
    {
        [JsonProperty("General")]
        General,
        [JsonProperty("Program")]
        Program,
        [JsonProperty("Orientation")]
        Orientation,
        [JsonProperty("Specialization")]
        Specialization,
        [JsonProperty("Individual")]
        Individual,
        [JsonProperty("Project")]
        Project,
        [JsonProperty("Elementary")]
        Elementary,
    }

    public static class GradeUpperSecondaryUpdateSectionExtension
    {
        public static string Value(this GradeUpperSecondaryUpdateSection value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GradeUpperSecondaryUpdateSection ToEnum(this string value)
        {
            foreach(var field in typeof(GradeUpperSecondaryUpdateSection).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GradeUpperSecondaryUpdateSection)
                    {
                        return (GradeUpperSecondaryUpdateSection)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GradeUpperSecondaryUpdateSection");
        }
    }
}