//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Request body.
    /// </summary>
    public class GradeUpperSecondaryUpdate
    {
        /// <summary>
        /// ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key.
        /// </summary>
        [JsonProperty("external")]
        public GradeUpperSecondaryUpdateExternal? External { get; set; }

        /// <summary>
        /// The language code for the grade, used when the course is taught in a specific language.
        /// </summary>
        [JsonProperty("languageCode")]
        public string? LanguageCode { get; set; } = null;

        /// <summary>
        /// The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher1EmployeeID")]
        public string? Teacher1EmployeeID { get; set; } = null;

        /// <summary>
        /// The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher2EmployeeID")]
        public string? Teacher2EmployeeID { get; set; } = null;

        /// <summary>
        /// The grade awarded to the student.
        /// </summary>
        [JsonProperty("grade")]
        public GradeUpperSecondaryUpdateGrade? Grade { get; set; } = null;

        /// <summary>
        /// The date the grade was awarded.
        /// </summary>
        [JsonProperty("gradeDate")]
        public DateOnly? GradeDate { get; set; } = null;

        /// <summary>
        /// A comment about the grade from the teacher.
        /// </summary>
        [JsonProperty("gradeComment")]
        public string? GradeComment { get; set; } = null;

        /// <summary>
        /// The extent of the course for this student.
        /// </summary>
        [JsonProperty("extent")]
        public GradeUpperSecondaryUpdateExtent? Extent { get; set; } = null;

        /// <summary>
        /// The school year of the student at the time the grade was awarded.
        /// </summary>
        [JsonProperty("schoolYear")]
        public GradeUpperSecondaryUpdateSchoolYear? SchoolYear { get; set; } = null;

        /// <summary>
        /// The section/type of the course in the student's study plan.
        /// </summary>
        [JsonProperty("section")]
        public GradeUpperSecondaryUpdateSection? Section { get; set; } = null;

        /// <summary>
        /// A comment from the teacher about the student's performance.
        /// </summary>
        [JsonProperty("teacherComment")]
        public string? TeacherComment { get; set; } = null;

        /// <summary>
        /// Whether this course grade should be included when calculating the student's final grade certificate.
        /// </summary>
        [JsonProperty("includeOnFinalGrade")]
        public bool IncludeOnFinalGrade { get; set; } = default!;

        /// <summary>
        /// The title of the program this course belongs to. Used to associate the course with a specific educational program.
        /// </summary>
        [JsonProperty("programTitle")]
        public string? ProgramTitle { get; set; } = null;

        /// <summary>
        /// The date the student started the course.
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly? StartDate { get; set; } = null;

        /// <summary>
        /// The date the student finished the course.
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;
    }
}