//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Response for GradeElementary List operation - returns a paginated list of GradeElementary.
    /// </summary>
    public class GradeElementaryList
    {
        /// <summary>
        /// Array of GradeElementary objects.
        /// </summary>
        [JsonProperty("data")]
        public List<GradeElementary>? Data { get; set; }

        /// <summary>
        /// Pagination information.
        /// </summary>
        [JsonProperty("pagination")]
        public GradeElementaryListPagination? Pagination { get; set; }
    }
}