//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The school year of the student at the time the grade was awarded.
    /// </summary>
    public enum GradeUpperSecondaryCreateSchoolYear
    {
        [JsonProperty("1")]
        One,
        [JsonProperty("2")]
        Two,
        [JsonProperty("3")]
        Three,
    }

    public static class GradeUpperSecondaryCreateSchoolYearExtension
    {
        public static string Value(this GradeUpperSecondaryCreateSchoolYear value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GradeUpperSecondaryCreateSchoolYear ToEnum(this string value)
        {
            foreach(var field in typeof(GradeUpperSecondaryCreateSchoolYear).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GradeUpperSecondaryCreateSchoolYear)
                    {
                        return (GradeUpperSecondaryCreateSchoolYear)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GradeUpperSecondaryCreateSchoolYear");
        }
    }
}