//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Request body.
    /// </summary>
    public class GradeElementaryCreate
    {
        /// <summary>
        /// ExternalRequest is the External-object used on Create and Update operations. Only SourceID can be set — the Source field is derived from the API key.
        /// </summary>
        [JsonProperty("external")]
        public GradeElementaryCreateExternal? External { get; set; }

        /// <summary>
        /// The ID of the student the grade belongs to. Must reference a student within the organization who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("studentID")]
        public string StudentID { get; set; } = default!;

        /// <summary>
        /// The ID of the school where the student received the grade. Must reference a school within the organization.
        /// </summary>
        [JsonProperty("schoolID")]
        public string SchoolID { get; set; } = default!;

        /// <summary>
        /// The subject code as defined by the Swedish school authorities (e.g. "MA" for Mathematics, "SV" for Swedish).
        /// </summary>
        [JsonProperty("subjectCode")]
        public string SubjectCode { get; set; } = default!;

        /// <summary>
        /// The language code for the grade, used when the subject is taught in a specific language (e.g. mother tongue instruction).
        /// </summary>
        [JsonProperty("languageCode")]
        public string? LanguageCode { get; set; } = null;

        /// <summary>
        /// The academic year in which the grade was awarded, in the format YYYY/YYYY (e.g. "2024/2025").
        /// </summary>
        [JsonProperty("academicYear")]
        public string AcademicYear { get; set; } = default!;

        /// <summary>
        /// The school term in which the grade was awarded.
        /// </summary>
        [JsonProperty("term")]
        public GradeElementaryCreateTerm Term { get; set; } = default!;

        /// <summary>
        /// The school year of the student at the time the grade was awarded.
        /// </summary>
        [JsonProperty("schoolYear")]
        public GradeElementaryCreateSchoolYear SchoolYear { get; set; } = default!;

        /// <summary>
        /// The ID of the primary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher1EmployeeID")]
        public string? Teacher1EmployeeID { get; set; } = null;

        /// <summary>
        /// The ID of the secondary teacher responsible for the grade. Must reference an Employee who has an active placement at the school referenced by SchoolID.
        /// </summary>
        [JsonProperty("teacher2EmployeeID")]
        public string? Teacher2EmployeeID { get; set; } = null;

        /// <summary>
        /// The grade awarded to the student.
        /// </summary>
        [JsonProperty("grade")]
        public GradeElementaryCreateGrade? Grade { get; set; } = null;

        /// <summary>
        /// The date the grade was awarded.
        /// </summary>
        [JsonProperty("gradeDate")]
        public DateOnly? GradeDate { get; set; } = null;

        /// <summary>
        /// Whether this is the final grade for the student in this subject. A final grade is the official grade used on the student's grade certificate.
        /// </summary>
        [JsonProperty("finalGrade")]
        public bool FinalGrade { get; set; } = default!;

        /// <summary>
        /// Whether the grading period has ended for this student in this subject.
        /// </summary>
        [JsonProperty("isEnded")]
        public bool IsEnded { get; set; } = default!;

        /// <summary>
        /// A comment from the school about the grade, visible to the student and guardians.
        /// </summary>
        [JsonProperty("schoolComment")]
        public string? SchoolComment { get; set; } = null;
    }
}