//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Greater than or equal filters for Group
    /// </summary>
    public class GroupSearchGreaterOrEqual
    {

        /// <summary>
        /// Metadata information for the Group
        /// </summary>
        [JsonProperty("meta")]
        public GroupSearchGreaterOrEqualMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GroupSearchGreaterOrEqualExternal? External { get; set; } = null;
    }
}