//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Group holds the information about a group of students.
    /// </summary>
    public class Group
    {

        /// <summary>
        /// Unique identifier for the Group
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Metadata information for the Group
        /// </summary>
        [JsonProperty("meta")]
        public GroupMeta? Meta { get; set; }

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GroupExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the school the group belongs to
        /// </summary>
        [JsonProperty("schoolID")]
        public string SchoolID { get; set; } = default!;

        /// <summary>
        /// If the category is Education, the ModeratorIDs have to be employees and the MemberIDs have to be students of the school. If the category is Other, it will not be possible to use the IsClass, IsChildcare and IsMentor fields.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("category")]
        public GroupCategory1? Category { get; set; } = Meitner.Models.Components.GroupCategory1.Education;

        /// <summary>
        /// The title of the group, must be unique within the school.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// The types of the group
        /// </summary>
        [JsonProperty("types")]
        public List<GroupType>? Types { get; set; }

        /// <summary>
        /// The IDs of the moderators of the group.  Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Moderators have to be employees of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("moderatorIDs")]
        public List<string>? ModeratorIDs { get; set; }

        /// <summary>
        /// The IDs of the members of the group. Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Members have to be students of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("memberIDs")]
        public List<string>? MemberIDs { get; set; }
    }
}