//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    
    /// <summary>
    /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
    /// </summary>
    public class GroupFilterGreaterOrEqualExternal
    {
    }
}