//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The types of the group. Note: For preschools (FS), Class and Childcare types are automatically paired. Adding Class will automatically include Childcare, and adding Childcare will automatically include Class.
    /// </summary>
    public enum GroupFilterNotEqualsTypes
    {
        [JsonProperty("Class")]
        Class,
        [JsonProperty("Childcare")]
        Childcare,
        [JsonProperty("Mentor")]
        Mentor,
    }

    public static class GroupFilterNotEqualsTypesExtension
    {
        public static string Value(this GroupFilterNotEqualsTypes value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GroupFilterNotEqualsTypes ToEnum(this string value)
        {
            foreach(var field in typeof(GroupFilterNotEqualsTypes).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GroupFilterNotEqualsTypes)
                    {
                        return (GroupFilterNotEqualsTypes)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GroupFilterNotEqualsTypes");
        }
    }
}