//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Equality filters for Group
    /// </summary>
    public class GroupSearchEquals
    {

        /// <summary>
        /// Unique identifier for the Group
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Metadata information for the Group
        /// </summary>
        [JsonProperty("meta")]
        public GroupSearchEqualsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GroupSearchEqualsExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the school the group belongs to
        /// </summary>
        [JsonProperty("schoolID")]
        public string? SchoolID { get; set; } = null;

        /// <summary>
        /// If the category is Education, the ModeratorIDs have to be employees and the MemberIDs have to be students of the school. If the category is Other, it will not be possible to use the IsClass, IsChildcare and IsMentor fields.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("category")]
        public GroupSearchEqualsCategory? Category { get; set; } = null;

        /// <summary>
        /// The title of the group, must be unique within the school.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The types of the group
        /// </summary>
        [JsonProperty("types")]
        public EqualsTypesRequestBody? Types { get; set; } = null;

        /// <summary>
        /// The IDs of the moderators of the group.  Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Moderators have to be employees of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("moderatorIDs")]
        public string? ModeratorIDs { get; set; } = null;

        /// <summary>
        /// The IDs of the members of the group. Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Members have to be students of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("memberIDs")]
        public string? MemberIDs { get; set; } = null;
    }
}