//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// If the category is Education, the ModeratorIDs have to be employees and the MemberIDs have to be students of the school. If the category is Other, it will not be possible to use the IsClass, IsChildcare and IsMentor fields.
    /// </summary>
    public enum GroupFilterEqualsCategory
    {
        [JsonProperty("Education")]
        Education,
        [JsonProperty("Other")]
        Other,
    }

    public static class GroupFilterEqualsCategoryExtension
    {
        public static string Value(this GroupFilterEqualsCategory value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GroupFilterEqualsCategory ToEnum(this string value)
        {
            foreach(var field in typeof(GroupFilterEqualsCategory).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GroupFilterEqualsCategory)
                    {
                        return (GroupFilterEqualsCategory)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GroupFilterEqualsCategory");
        }
    }
}