//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Null filters for Group
    /// </summary>
    public class GroupSearchNull
    {

        /// <summary>
        /// Metadata information for the Group
        /// </summary>
        [JsonProperty("meta")]
        public GroupSearchNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GroupSearchNullExternal? External { get; set; } = null;

        /// <summary>
        /// The types of the group
        /// </summary>
        [JsonProperty("types")]
        public bool? Types { get; set; } = null;

        /// <summary>
        /// The IDs of the moderators of the group.  Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Moderators have to be employees of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("moderatorIDs")]
        public bool? ModeratorIDs { get; set; } = null;

        /// <summary>
        /// The IDs of the members of the group. Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Members have to be students of the school.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("memberIDs")]
        public bool? MemberIDs { get; set; } = null;
    }
}