//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Not contains filters for Group.
    /// </summary>
    public class GroupSearchNotContains
    {
        /// <summary>
        /// Unique identifier for the Group.
        /// </summary>
        [JsonProperty("id")]
        public List<string>? Id { get; set; }

        /// <summary>
        /// Metadata information for the Group.
        /// </summary>
        [JsonProperty("meta")]
        public GroupSearchNotContainsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the employee from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GroupSearchNotContainsExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the school the group belongs to.
        /// </summary>
        [JsonProperty("schoolID")]
        public List<string>? SchoolID { get; set; }

        /// <summary>
        /// If the category is Education, the ModeratorIDs have to be employees and the MemberIDs have to be students of the school. If the category is Other, it will not be possible to use the IsClass, IsChildcare and IsMentor fields.
        /// </summary>
        [JsonProperty("category")]
        public List<GroupCategory>? Category { get; set; }

        /// <summary>
        /// The title of the group, must be unique within the school.
        /// </summary>
        [JsonProperty("title")]
        public List<string>? Title { get; set; }

        /// <summary>
        /// The types of the group. Note: For preschools (FS), Class and Childcare types are automatically paired. Adding Class will automatically include Childcare, and adding Childcare will automatically include Class.
        /// </summary>
        [JsonProperty("types")]
        public List<GroupType>? Types { get; set; }

        /// <summary>
        /// The IDs of the moderators of the group.  Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Moderators have to be employees of the school.
        /// </summary>
        [JsonProperty("moderatorIDs")]
        public List<string>? ModeratorIDs { get; set; }

        /// <summary>
        /// The IDs of the members of the group. Can be any user type (Student, Employee, Guardian) if the Category is Other. If the Category is Education, the Members have to be students of the school.
        /// </summary>
        [JsonProperty("memberIDs")]
        public List<string>? MemberIDs { get; set; }
    }
}