//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// The address of the guardian.
    /// </summary>
    public class GuardianSearchNotContainsAddress
    {
        /// <summary>
        /// The postal address of the address.
        /// </summary>
        [JsonProperty("postalAddress")]
        public List<string>? PostalAddress { get; set; }

        /// <summary>
        /// The postal code (also known as ZIP or postcode) of the address, used together with the city to identify the delivery area.
        /// </summary>
        [JsonProperty("postalCode")]
        public List<string>? PostalCode { get; set; }

        /// <summary>
        /// The city of the address.
        /// </summary>
        [JsonProperty("postalCity")]
        public List<string>? PostalCity { get; set; }

        /// <summary>
        /// The ISO 3166-1 alpha-3 country code of the address (e.g. "SWE" for Sweden).
        /// </summary>
        [JsonProperty("countryCode")]
        public List<string>? CountryCode { get; set; }

        /// <summary>
        /// The municipality code of the address.
        /// </summary>
        [JsonProperty("municipalityCode")]
        public List<string>? MunicipalityCode { get; set; }
    }
}