//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Filter object for Guardian.
    /// </summary>
    public class GuardianFilter
    {
        /// <summary>
        /// Equality filters for Guardian.
        /// </summary>
        [JsonProperty("equals")]
        public GuardianFilterEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for Guardian.
        /// </summary>
        [JsonProperty("notEquals")]
        public GuardianFilterNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for Guardian.
        /// </summary>
        [JsonProperty("greaterThan")]
        public GuardianFilterGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for Guardian.
        /// </summary>
        [JsonProperty("smallerThan")]
        public GuardianFilterSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for Guardian.
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public GuardianFilterGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for Guardian.
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public GuardianFilterSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for Guardian.
        /// </summary>
        [JsonProperty("contains")]
        public GuardianFilterContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for Guardian.
        /// </summary>
        [JsonProperty("notContains")]
        public GuardianFilterNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for Guardian.
        /// </summary>
        [JsonProperty("like")]
        public GuardianFilterLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for Guardian.
        /// </summary>
        [JsonProperty("notLike")]
        public GuardianFilterNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for Guardian.
        /// </summary>
        [JsonProperty("null")]
        public GuardianFilterNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for Guardian.
        /// </summary>
        [JsonProperty("notNull")]
        public GuardianFilterNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition.
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the Guardian, useful for more complex filters.
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<GuardianFilter>? NestedFilters { get; set; }
    }
}