//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Not null filters for Guardian.
    /// </summary>
    public class GuardianSearchNotNull
    {
        /// <summary>
        /// Metadata information for the Guardian.
        /// </summary>
        [JsonProperty("meta")]
        public GuardianSearchNotNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the guardian from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public GuardianSearchNotNullExternal? External { get; set; } = null;

        /// <summary>
        /// The address of the guardian.
        /// </summary>
        [JsonProperty("address")]
        public GuardianSearchNotNullAddress? Address { get; set; } = null;

        /// <summary>
        /// The email address of the guardian, will be used for communication with the guardian from the system and must be unique within the organization.<br/>
        /// Can be used to login to the system if password-authentication is enabled for the organization.
        /// </summary>
        [JsonProperty("emailAddress1")]
        public bool? EmailAddress1 { get; set; } = null;

        /// <summary>
        /// The secondary email address of the guardian, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("emailAddress2")]
        public bool? EmailAddress2 { get; set; } = null;

        /// <summary>
        /// The primary phone number of the guardian, will be used for communication with the guardian from the system.
        /// </summary>
        [JsonProperty("phoneNumber1")]
        public bool? PhoneNumber1 { get; set; } = null;

        /// <summary>
        /// The secondary phone number of the guardian, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("phoneNumber2")]
        public bool? PhoneNumber2 { get; set; } = null;

        /// <summary>
        /// The IDs of the students the guardian is responsible for.
        /// </summary>
        [JsonProperty("studentIDs")]
        public bool? StudentIDs { get; set; } = null;
    }
}