//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The roles of the employee
    /// </summary>
    public enum NotEqualsRoles
    {
        [JsonProperty("Admin")]
        Admin,
        [JsonProperty("CareTeam")]
        CareTeam,
        [JsonProperty("Manager")]
        Manager,
        [JsonProperty("OtherPersonnel")]
        OtherPersonnel,
        [JsonProperty("Scheduler")]
        Scheduler,
        [JsonProperty("Teacher")]
        Teacher,
    }

    public static class NotEqualsRolesExtension
    {
        public static string Value(this NotEqualsRoles value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NotEqualsRoles ToEnum(this string value)
        {
            foreach(var field in typeof(NotEqualsRoles).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is NotEqualsRoles)
                    {
                        return (NotEqualsRoles)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum NotEqualsRoles");
        }
    }

}