//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The types of the group. A group can have multiple types simultaneously. For preschools (FS), Class and Childcare types are automatically paired - adding Class will automatically include Childcare, and vice versa. Integration note for Mentor type - when importing groups from external systems, it can be difficult to determine whether a group should have the Mentor type. One recommended approach is to not include the Mentor type when creating or updating groups via the API, allowing school administrators to manually configure the Mentor type in Meitner as needed. When updating a group, you can preserve existing types by reading the current group state first and only modifying the specific types your integration manages (e.g., Class, Childcare). This ensures the Mentor type remains under administrator control.
    /// </summary>
    public enum NotEqualsTypesRequestBody
    {
        [JsonProperty("Class")]
        Class,
        [JsonProperty("Childcare")]
        Childcare,
        [JsonProperty("Mentor")]
        Mentor,
    }

    public static class NotEqualsTypesRequestBodyExtension
    {
        public static string Value(this NotEqualsTypesRequestBody value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NotEqualsTypesRequestBody ToEnum(this string value)
        {
            foreach(var field in typeof(NotEqualsTypesRequestBody).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is NotEqualsTypesRequestBody)
                    {
                        return (NotEqualsTypesRequestBody)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum NotEqualsTypesRequestBody");
        }
    }
}