//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Not contains filters for School.
    /// </summary>
    public class SchoolFilterNotContains
    {
        /// <summary>
        /// Unique identifier for the School.
        /// </summary>
        [JsonProperty("id")]
        public List<string>? Id { get; set; }

        /// <summary>
        /// Metadata information for the School.
        /// </summary>
        [JsonProperty("meta")]
        public SchoolFilterNotContainsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the school from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public SchoolFilterNotContainsExternal? External { get; set; } = null;

        /// <summary>
        /// The title of the school.
        /// </summary>
        [JsonProperty("title")]
        public List<string>? Title { get; set; }

        /// <summary>
        /// The School Unit Code provided by SCB, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("unitCode")]
        public List<string>? UnitCode { get; set; }

        /// <summary>
        /// The School Code provided by CSN, required for reports to CSN.
        /// </summary>
        [JsonProperty("csnSchoolCode")]
        public List<string>? CsnSchoolCode { get; set; }

        /// <summary>
        /// Municipality code of the school, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("municipalityCode")]
        public List<string>? MunicipalityCode { get; set; }

        /// <summary>
        /// Type of schooling provided at the school.
        /// </summary>
        [JsonProperty("schoolType")]
        public List<SchoolType>? SchoolType { get; set; }
    }
}