//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Not null filters for School.
    /// </summary>
    public class SchoolFilterNotNull
    {
        /// <summary>
        /// Metadata information for the School.
        /// </summary>
        [JsonProperty("meta")]
        public SchoolFilterNotNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the school from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public SchoolFilterNotNullExternal? External { get; set; } = null;

        /// <summary>
        /// The School Unit Code provided by SCB, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("unitCode")]
        public bool? UnitCode { get; set; } = null;

        /// <summary>
        /// The School Code provided by CSN, required for reports to CSN.
        /// </summary>
        [JsonProperty("csnSchoolCode")]
        public bool? CsnSchoolCode { get; set; } = null;

        /// <summary>
        /// Municipality code of the school, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("municipalityCode")]
        public bool? MunicipalityCode { get; set; } = null;
    }
}