//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Request body.
    /// </summary>
    public class SchoolCreate
    {
        /// <summary>
        /// External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the school, the Source-field is not included.
        /// </summary>
        [JsonProperty("external")]
        public SchoolCreateExternal? External { get; set; }

        /// <summary>
        /// The title of the school.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// The School Unit Code provided by SCB, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("unitCode")]
        public string? UnitCode { get; set; } = null;

        /// <summary>
        /// The School Code provided by CSN, required for reports to CSN.
        /// </summary>
        [JsonProperty("csnSchoolCode")]
        public string? CsnSchoolCode { get; set; } = null;

        /// <summary>
        /// Municipality code of the school, is used in reports and printed on grade documents.
        /// </summary>
        [JsonProperty("municipalityCode")]
        public string? MunicipalityCode { get; set; } = null;

        /// <summary>
        /// Type of schooling provided at the school.
        /// </summary>
        [JsonProperty("schoolType")]
        public SchoolCreateSchoolType SchoolType { get; set; } = default!;
    }
}