//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Smaller than or equal filters for School.
    /// </summary>
    public class SchoolFilterSmallerOrEqual
    {
        /// <summary>
        /// Metadata information for the School.
        /// </summary>
        [JsonProperty("meta")]
        public SchoolFilterSmallerOrEqualMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the school from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public SchoolFilterSmallerOrEqualExternal? External { get; set; } = null;
    }
}