//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Inequality filters for School
    /// </summary>
    public class SchoolFilterNotEquals
    {

        /// <summary>
        /// Unique identifier for the School
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Metadata information for the School
        /// </summary>
        [JsonProperty("meta")]
        public SchoolFilterNotEqualsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the school from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public SchoolFilterNotEqualsExternal? External { get; set; } = null;

        /// <summary>
        /// The title of the school
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The School Unit Code provided by SCB, is used in reports and printed on grade documents
        /// </summary>
        [JsonProperty("unitCode")]
        public string? UnitCode { get; set; } = null;

        /// <summary>
        /// The School Code provided by CSN, required for reports to CSN
        /// </summary>
        [JsonProperty("csnSchoolCode")]
        public string? CsnSchoolCode { get; set; } = null;

        /// <summary>
        /// Municipality code of the school, is used in reports and printed on grade documents
        /// </summary>
        [JsonProperty("municipalityCode")]
        public string? MunicipalityCode { get; set; } = null;

        /// <summary>
        /// Type of schooling provided at the school
        /// </summary>
        [JsonProperty("schoolType")]
        public SchoolFilterNotEqualsSchoolType? SchoolType { get; set; } = null;
    }
}