//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;

    public class SecurityOption2
    {
        [SpeakeasyMetadata("security:scheme=true,type=oauth2,subType=client_credentials,name=clientID")]
        public string ClientID { get; set; } = default!;

        [SpeakeasyMetadata("security:scheme=true,type=oauth2,subType=client_credentials,name=clientSecret")]
        public string ClientSecret { get; set; } = default!;

        public string TokenURL { get; set; } = "/oauth/token";
    }
}