//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    
    public class Security
    {

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=Client-ID")]
        public string ClientCredentials { get; set; } = default!;

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=Client-Secret")]
        public string ClientSecret { get; set; } = default!;
    }
}