//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// NOT LIKE filters for StudentPlacement.
    /// </summary>
    public class StudentPlacementFilterNotLike
    {
        /// <summary>
        /// Metadata information for the StudentPlacement.
        /// </summary>
        [JsonProperty("meta")]
        public StudentPlacementFilterNotLikeMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentPlacementFilterNotLikeExternal? External { get; set; } = null;

        /// <summary>
        /// The mother tongue of the student. Language codes follow the ISO 639-3 standard (three-letter codes).
        /// </summary>
        [JsonProperty("motherTongue")]
        public string? MotherTongue { get; set; } = null;

        /// <summary>
        /// The language code for the student's modern language in school choice (Skolans val). Language codes follow the ISO 639-2 standard (three-letter codes).
        /// </summary>
        [JsonProperty("modernLanguageInSchoolChoice")]
        public string? ModernLanguageInSchoolChoice { get; set; } = null;

        /// <summary>
        /// The language code for the student's modern language in language choice (Språkval, M2, B-språk). Language codes follow the ISO 639-2 standard (three-letter codes).
        /// </summary>
        [JsonProperty("modernLanguageInLanguageChoice")]
        public string? ModernLanguageInLanguageChoice { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the student, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public string? ArchiveYear { get; set; } = null;
    }
}