//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// External is a reusable object that can be used to store external information about the student placement from another system, used for third-party integration tracking.
    /// </summary>
    public class StudentPlacementSearchContainsExternal
    {
        /// <summary>
        /// The ID of the external source.
        /// </summary>
        [JsonProperty("sourceID")]
        public List<string>? SourceID { get; set; }

        /// <summary>
        /// The source of the external information.
        /// </summary>
        [JsonProperty("source")]
        public List<string>? Source { get; set; }
    }
}