//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Null filters for StudentPlacement.
    /// </summary>
    public class StudentPlacementSearchNull
    {
        /// <summary>
        /// Metadata information for the StudentPlacement.
        /// </summary>
        [JsonProperty("meta")]
        public StudentPlacementSearchNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentPlacementSearchNullExternal? External { get; set; } = null;

        /// <summary>
        /// The school year the student is placed in.
        /// </summary>
        [JsonProperty("schoolYear")]
        public bool? SchoolYear { get; set; } = null;

        /// <summary>
        /// The mother tongue of the student. Language codes follow the ISO 639-3 standard (three-letter codes).
        /// </summary>
        [JsonProperty("motherTongue")]
        public bool? MotherTongue { get; set; } = null;

        /// <summary>
        /// The modern language alternative for the student.
        /// </summary>
        [JsonProperty("modernLanguageAlternative")]
        public bool? ModernLanguageAlternative { get; set; } = null;

        /// <summary>
        /// The language code for the student's modern language in school choice (Skolans val). Language codes follow the ISO 639-2 standard (three-letter codes).
        /// </summary>
        [JsonProperty("modernLanguageInSchoolChoice")]
        public bool? ModernLanguageInSchoolChoice { get; set; } = null;

        /// <summary>
        /// The language code for the student's modern language in language choice (Språkval, M2, B-språk). Language codes follow the ISO 639-2 standard (three-letter codes).
        /// </summary>
        [JsonProperty("modernLanguageInLanguageChoice")]
        public bool? ModernLanguageInLanguageChoice { get; set; } = null;

        /// <summary>
        /// The end date of the placement.
        /// </summary>
        [JsonProperty("endDate")]
        public bool? EndDate { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the student, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public bool? ArchiveYear { get; set; } = null;

        /// <summary>
        /// The timestamp the placement was archived for the student.
        /// </summary>
        [JsonProperty("archivedAt")]
        public bool? ArchivedAt { get; set; } = null;
    }
}