//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Filter object for StudentPlacement
    /// </summary>
    public class StudentPlacementFilter
    {

        /// <summary>
        /// Equality filters for StudentPlacement
        /// </summary>
        [JsonProperty("equals")]
        public StudentPlacementFilterEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for StudentPlacement
        /// </summary>
        [JsonProperty("notEquals")]
        public StudentPlacementFilterNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for StudentPlacement
        /// </summary>
        [JsonProperty("greaterThan")]
        public StudentPlacementFilterGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for StudentPlacement
        /// </summary>
        [JsonProperty("smallerThan")]
        public StudentPlacementFilterSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for StudentPlacement
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public StudentPlacementFilterGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for StudentPlacement
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public StudentPlacementFilterSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for StudentPlacement
        /// </summary>
        [JsonProperty("contains")]
        public StudentPlacementFilterContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for StudentPlacement
        /// </summary>
        [JsonProperty("notContains")]
        public StudentPlacementFilterNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for StudentPlacement
        /// </summary>
        [JsonProperty("like")]
        public StudentPlacementFilterLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for StudentPlacement
        /// </summary>
        [JsonProperty("notLike")]
        public StudentPlacementFilterNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for StudentPlacement
        /// </summary>
        [JsonProperty("null")]
        public StudentPlacementFilterNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for StudentPlacement
        /// </summary>
        [JsonProperty("notNull")]
        public StudentPlacementFilterNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the StudentPlacement, useful for more complex filters
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<StudentPlacementFilter>? NestedFilters { get; set; }
    }
}