//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The school type for the student, if not provided on Create, the school type will be fetched from the school.
    /// </summary>
    public enum StudentPlacementCreateSchoolType
    {
        [JsonProperty("GR")]
        Gr,
        [JsonProperty("GRAN")]
        Gran,
        [JsonProperty("GY")]
        Gy,
        [JsonProperty("GYAN")]
        Gyan,
        [JsonProperty("FS")]
        Fs,
    }

    public static class StudentPlacementCreateSchoolTypeExtension
    {
        public static string Value(this StudentPlacementCreateSchoolType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static StudentPlacementCreateSchoolType ToEnum(this string value)
        {
            foreach(var field in typeof(StudentPlacementCreateSchoolType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is StudentPlacementCreateSchoolType)
                    {
                        return (StudentPlacementCreateSchoolType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum StudentPlacementCreateSchoolType");
        }
    }
}