//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// StudentPlacement holds the placement information about a student in a specific school.
    /// </summary>
    public class StudentPlacement
    {

        /// <summary>
        /// Unique identifier for the StudentPlacement
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Metadata information for the StudentPlacement
        /// </summary>
        [JsonProperty("meta")]
        public StudentPlacementMeta? Meta { get; set; }

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentPlacementExternal? External { get; set; } = null;

        /// <summary>
        /// The ID of the student the placement belongs to
        /// </summary>
        [JsonProperty("studentID")]
        public string StudentID { get; set; } = default!;

        /// <summary>
        /// The ID of the school the student is placed in
        /// </summary>
        [JsonProperty("schoolID")]
        public string SchoolID { get; set; } = default!;

        /// <summary>
        /// The school type for the student, if not provided on Create, the school type will be fetched from the school.
        /// </summary>
        [JsonProperty("schoolType")]
        public StudentPlacementSchoolType1 SchoolType { get; set; } = default!;

        /// <summary>
        /// The school year the student is placed in
        /// </summary>
        [JsonProperty("schoolYear")]
        public StudentPlacementSchoolYear? SchoolYear { get; set; } = null;

        /// <summary>
        /// Whether the student has childcare
        /// </summary>
        [JsonProperty("hasChildcare")]
        public bool? HasChildcare { get; set; } = false;

        /// <summary>
        /// The mother tongue of the student
        /// </summary>
        [JsonProperty("motherTongue")]
        public string? MotherTongue { get; set; } = null;

        /// <summary>
        /// The start date of the placement
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly StartDate { get; set; } = default!;

        /// <summary>
        /// The end date of the placement
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the student, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public string? ArchiveYear { get; set; } = null;

        /// <summary>
        /// The timestamp the placement was archived for the student
        /// </summary>
        [JsonProperty("archivedAt")]
        public DateTime? ArchivedAt { get; set; } = null;
    }
}