//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Filter object for Student
    /// </summary>
    public class StudentFilter
    {

        /// <summary>
        /// Equality filters for Student
        /// </summary>
        [JsonProperty("equals")]
        public StudentFilterEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for Student
        /// </summary>
        [JsonProperty("notEquals")]
        public StudentFilterNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for Student
        /// </summary>
        [JsonProperty("greaterThan")]
        public StudentFilterGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for Student
        /// </summary>
        [JsonProperty("smallerThan")]
        public StudentFilterSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for Student
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public StudentFilterGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for Student
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public StudentFilterSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for Student
        /// </summary>
        [JsonProperty("contains")]
        public StudentFilterContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for Student
        /// </summary>
        [JsonProperty("notContains")]
        public StudentFilterNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for Student
        /// </summary>
        [JsonProperty("like")]
        public StudentFilterLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for Student
        /// </summary>
        [JsonProperty("notLike")]
        public StudentFilterNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for Student
        /// </summary>
        [JsonProperty("null")]
        public StudentFilterNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for Student
        /// </summary>
        [JsonProperty("notNull")]
        public StudentFilterNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the Student, useful for more complex filters
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<StudentFilter>? NestedFilters { get; set; }
    }
}