//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Not null filters for Student.
    /// </summary>
    public class StudentSearchNotNull
    {
        /// <summary>
        /// Metadata information for the Student.
        /// </summary>
        [JsonProperty("meta")]
        public StudentSearchNotNullMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentSearchNotNullExternal? External { get; set; } = null;

        /// <summary>
        /// The gender of the student.
        /// </summary>
        [JsonProperty("gender")]
        public bool? Gender { get; set; } = null;

        /// <summary>
        /// The date of birth of the student.
        /// </summary>
        [JsonProperty("dateOfBirth")]
        public bool? DateOfBirth { get; set; } = null;

        /// <summary>
        /// The address of the student.
        /// </summary>
        [JsonProperty("address")]
        public StudentSearchNotNullAddress? Address { get; set; } = null;

        /// <summary>
        /// The primary email address of the student, will be used for communication with the student from the system and must be unique within the organization.<br/>
        /// Can be used to login to the system if password-authentication is enabled for the organization.
        /// </summary>
        [JsonProperty("emailAddress1")]
        public bool? EmailAddress1 { get; set; } = null;

        /// <summary>
        /// The secondary email address of the student, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("emailAddress2")]
        public bool? EmailAddress2 { get; set; } = null;

        /// <summary>
        /// The primary phone number of the student, will be used for communication with the student from the system.
        /// </summary>
        [JsonProperty("phoneNumber1")]
        public bool? PhoneNumber1 { get; set; } = null;

        /// <summary>
        /// The secondary phone number of the student, will not be used within the system, but will be displayed for contact information.
        /// </summary>
        [JsonProperty("phoneNumber2")]
        public bool? PhoneNumber2 { get; set; } = null;
    }
}