//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Filter criteria to search for specific records
    /// </summary>
    public class StudentSearchFilter
    {

        /// <summary>
        /// Equality filters for Student
        /// </summary>
        [JsonProperty("equals")]
        public StudentSearchEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for Student
        /// </summary>
        [JsonProperty("notEquals")]
        public StudentSearchNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for Student
        /// </summary>
        [JsonProperty("greaterThan")]
        public StudentSearchGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for Student
        /// </summary>
        [JsonProperty("smallerThan")]
        public StudentSearchSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for Student
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public StudentSearchGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for Student
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public StudentSearchSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for Student
        /// </summary>
        [JsonProperty("contains")]
        public StudentSearchContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for Student
        /// </summary>
        [JsonProperty("notContains")]
        public StudentSearchNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for Student
        /// </summary>
        [JsonProperty("like")]
        public StudentSearchLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for Student
        /// </summary>
        [JsonProperty("notLike")]
        public StudentSearchNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for Student
        /// </summary>
        [JsonProperty("null")]
        public StudentSearchNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for Student
        /// </summary>
        [JsonProperty("notNull")]
        public StudentSearchNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the Student, useful for more complex filters
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<StudentFilter>? NestedFilters { get; set; }
    }
}