//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The school year the student is placed in
    /// </summary>
    public enum StudentPlacementCreateSchoolYear
    {
        [JsonProperty("0")]
        Zero,
        [JsonProperty("1")]
        One,
        [JsonProperty("2")]
        Two,
        [JsonProperty("3")]
        Three,
        [JsonProperty("4")]
        Four,
        [JsonProperty("5")]
        Five,
        [JsonProperty("6")]
        Six,
        [JsonProperty("7")]
        Seven,
        [JsonProperty("8")]
        Eight,
        [JsonProperty("9")]
        Nine,
    }

    public static class StudentPlacementCreateSchoolYearExtension
    {
        public static string Value(this StudentPlacementCreateSchoolYear value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static StudentPlacementCreateSchoolYear ToEnum(this string value)
        {
            foreach(var field in typeof(StudentPlacementCreateSchoolYear).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is StudentPlacementCreateSchoolYear)
                    {
                        return (StudentPlacementCreateSchoolYear)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum StudentPlacementCreateSchoolYear");
        }
    }

}