//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The gender of the student
    /// </summary>
    public enum StudentSearchEqualsGender
    {
        [JsonProperty("Female")]
        Female,
        [JsonProperty("Male")]
        Male,
        [JsonProperty("Other")]
        Other,
    }

    public static class StudentSearchEqualsGenderExtension
    {
        public static string Value(this StudentSearchEqualsGender value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static StudentSearchEqualsGender ToEnum(this string value)
        {
            foreach(var field in typeof(StudentSearchEqualsGender).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is StudentSearchEqualsGender)
                    {
                        return (StudentSearchEqualsGender)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum StudentSearchEqualsGender");
        }
    }

}