//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Standard error response object containing error code, message, and request ID
    /// </summary>
    public class StudentPlacementCreate422ResponseBodyError
    {

        /// <summary>
        /// The specific error code indicating the type of error
        /// </summary>
        [JsonProperty("code")]
        public ErrorCode Code { get; set; } = default!;

        /// <summary>
        /// Human-readable error message providing additional details
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;

        /// <summary>
        /// Unique identifier for the request that generated this error, used for logging and debugging
        /// </summary>
        [JsonProperty("requestID")]
        public string RequestID { get; set; } = default!;
    }
}