//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Metadata information for the StudentPlacement.
    /// </summary>
    public class StudentPlacementSearchNotNullMeta
    {
        /// <summary>
        /// User who created the resource.
        /// </summary>
        [JsonProperty("createdBy")]
        public bool? CreatedBy { get; set; } = null;

        /// <summary>
        /// Timestamp when the resource was last updated.
        /// </summary>
        [JsonProperty("updatedAt")]
        public bool? UpdatedAt { get; set; } = null;

        /// <summary>
        /// User who last updated the resource.
        /// </summary>
        [JsonProperty("updatedBy")]
        public bool? UpdatedBy { get; set; } = null;
    }
}