//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student, the Source-field is not included.
    /// </summary>
    public class StudentCreateExternal
    {
        /// <summary>
        /// The ID of the external source.
        /// </summary>
        [JsonProperty("sourceID")]
        public string SourceID { get; set; } = default!;
    }
}