//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Smaller than filters for Student
    /// </summary>
    public class StudentFilterSmallerThan
    {

        /// <summary>
        /// Metadata information for the Student
        /// </summary>
        [JsonProperty("meta")]
        public StudentFilterSmallerThanMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentFilterSmallerThanExternal? External { get; set; } = null;

        /// <summary>
        /// The date of birth of the student
        /// </summary>
        [JsonProperty("dateOfBirth")]
        public DateOnly? DateOfBirth { get; set; } = null;

        /// <summary>
        /// The address of the student
        /// </summary>
        [JsonProperty("address")]
        public StudentFilterSmallerThanAddress? Address { get; set; } = null;
    }
}