//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// LIKE filters for StudentPlacement
    /// </summary>
    public class StudentPlacementSearchLike
    {

        /// <summary>
        /// Metadata information for the StudentPlacement
        /// </summary>
        [JsonProperty("meta")]
        public StudentPlacementSearchLikeMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the student placement from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public StudentPlacementSearchLikeExternal? External { get; set; } = null;

        /// <summary>
        /// The mother tongue of the student
        /// </summary>
        [JsonProperty("motherTongue")]
        public string? MotherTongue { get; set; } = null;

        /// <summary>
        /// The year the placement was archived for the student, in the format YYYY_YYYY where the first year is the autumn and the second year is the spring.
        /// </summary>
        [JsonProperty("archiveYear")]
        public string? ArchiveYear { get; set; } = null;
    }
}