//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Request body
    /// </summary>
    public class StudentPlacementCreate
    {

        /// <summary>
        /// ExternalRequest is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the student placement, the Source-field is not included.
        /// </summary>
        [JsonProperty("external")]
        public StudentPlacementCreateExternal? External { get; set; }

        /// <summary>
        /// The ID of the student the placement belongs to
        /// </summary>
        [JsonProperty("studentID")]
        public string StudentID { get; set; } = default!;

        /// <summary>
        /// The ID of the school the student is placed in
        /// </summary>
        [JsonProperty("schoolID")]
        public string SchoolID { get; set; } = default!;

        /// <summary>
        /// The school type for the student, if not provided on Create, the school type will be fetched from the school.
        /// </summary>
        [JsonProperty("schoolType")]
        public StudentPlacementCreateSchoolType SchoolType { get; set; } = default!;

        /// <summary>
        /// The school year the student is placed in
        /// </summary>
        [JsonProperty("schoolYear")]
        public StudentPlacementCreateSchoolYear? SchoolYear { get; set; } = null;

        /// <summary>
        /// Whether the student has childcare
        /// </summary>
        [JsonProperty("hasChildcare")]
        public bool? HasChildcare { get; set; } = false;

        /// <summary>
        /// The mother tongue of the student
        /// </summary>
        [JsonProperty("motherTongue")]
        public string? MotherTongue { get; set; } = null;

        /// <summary>
        /// The start date of the placement
        /// </summary>
        [JsonProperty("startDate")]
        public DateOnly StartDate { get; set; } = default!;

        /// <summary>
        /// The end date of the placement
        /// </summary>
        [JsonProperty("endDate")]
        public DateOnly? EndDate { get; set; } = null;
    }
}