//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Response for StudentPlacement List operation - returns a paginated list of StudentPlacement
    /// </summary>
    public class StudentPlacementList
    {

        /// <summary>
        /// Array of StudentPlacement objects
        /// </summary>
        [JsonProperty("data")]
        public List<StudentPlacement>? Data { get; set; }

        /// <summary>
        /// Pagination information
        /// </summary>
        [JsonProperty("pagination")]
        public StudentPlacementListPagination? Pagination { get; set; }
    }
}