//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Request body.
    /// </summary>
    public class UnitUpdate
    {
        /// <summary>
        /// External is the External-object used on Update and Create operations, since it should only be allowed to set SourceID for the unit, the Source-field is not included.
        /// </summary>
        [JsonProperty("external")]
        public UnitUpdateExternal? External { get; set; }

        /// <summary>
        /// The title of the unit.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// The description of the unit.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;
    }
}