//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Greater than filters for Unit.
    /// </summary>
    public class UnitSearchGreaterThan
    {
        /// <summary>
        /// Metadata information for the Unit.
        /// </summary>
        [JsonProperty("meta")]
        public UnitSearchGreaterThanMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public UnitSearchGreaterThanExternal? External { get; set; } = null;
    }
}