//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The `Unit` resource represents an organizational unit that schools can belong to.<br/>
    /// This resource can be created, updated, listed, retrieved, and searched using the standard resource structure.
    /// </summary>
    public class Unit
    {
        /// <summary>
        /// Unique identifier for the Unit.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Metadata information for the Unit.
        /// </summary>
        [JsonProperty("meta")]
        public UnitMeta? Meta { get; set; }

        /// <summary>
        /// External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public UnitExternal? External { get; set; } = null;

        /// <summary>
        /// The title of the unit.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// The description of the unit.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;
    }
}