//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Contains filters for Unit.
    /// </summary>
    public class UnitSearchContains
    {
        /// <summary>
        /// Unique identifier for the Unit.
        /// </summary>
        [JsonProperty("id")]
        public List<string>? Id { get; set; }

        /// <summary>
        /// Metadata information for the Unit.
        /// </summary>
        [JsonProperty("meta")]
        public UnitSearchContainsMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public UnitSearchContainsExternal? External { get; set; } = null;

        /// <summary>
        /// The title of the unit.
        /// </summary>
        [JsonProperty("title")]
        public List<string>? Title { get; set; }

        /// <summary>
        /// The description of the unit.
        /// </summary>
        [JsonProperty("description")]
        public List<string>? Description { get; set; }
    }
}