//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// Filter object for Unit.
    /// </summary>
    public class UnitFilter
    {
        /// <summary>
        /// Equality filters for Unit.
        /// </summary>
        [JsonProperty("equals")]
        public UnitFilterEquals? Equals { get; set; } = null;

        /// <summary>
        /// Inequality filters for Unit.
        /// </summary>
        [JsonProperty("notEquals")]
        public UnitFilterNotEquals? NotEquals { get; set; } = null;

        /// <summary>
        /// Greater than filters for Unit.
        /// </summary>
        [JsonProperty("greaterThan")]
        public UnitFilterGreaterThan? GreaterThan { get; set; } = null;

        /// <summary>
        /// Smaller than filters for Unit.
        /// </summary>
        [JsonProperty("smallerThan")]
        public UnitFilterSmallerThan? SmallerThan { get; set; } = null;

        /// <summary>
        /// Greater than or equal filters for Unit.
        /// </summary>
        [JsonProperty("greaterOrEqual")]
        public UnitFilterGreaterOrEqual? GreaterOrEqual { get; set; } = null;

        /// <summary>
        /// Smaller than or equal filters for Unit.
        /// </summary>
        [JsonProperty("smallerOrEqual")]
        public UnitFilterSmallerOrEqual? SmallerOrEqual { get; set; } = null;

        /// <summary>
        /// Contains filters for Unit.
        /// </summary>
        [JsonProperty("contains")]
        public UnitFilterContains? Contains { get; set; } = null;

        /// <summary>
        /// Not contains filters for Unit.
        /// </summary>
        [JsonProperty("notContains")]
        public UnitFilterNotContains? NotContains { get; set; } = null;

        /// <summary>
        /// LIKE filters for Unit.
        /// </summary>
        [JsonProperty("like")]
        public UnitFilterLike? Like { get; set; } = null;

        /// <summary>
        /// NOT LIKE filters for Unit.
        /// </summary>
        [JsonProperty("notLike")]
        public UnitFilterNotLike? NotLike { get; set; } = null;

        /// <summary>
        /// Null filters for Unit.
        /// </summary>
        [JsonProperty("null")]
        public UnitFilterNull? Null { get; set; } = null;

        /// <summary>
        /// Not null filters for Unit.
        /// </summary>
        [JsonProperty("notNull")]
        public UnitFilterNotNull? NotNull { get; set; } = null;

        /// <summary>
        /// OrCondition decides if this filter is within an OR-condition or AND-condition.
        /// </summary>
        [JsonProperty("orCondition")]
        public bool OrCondition { get; set; } = default!;

        /// <summary>
        /// NestedFilters of the Unit, useful for more complex filters.
        /// </summary>
        [JsonProperty("nestedFilters")]
        public List<UnitFilter>? NestedFilters { get; set; }
    }
}