//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Components
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// LIKE filters for Unit.
    /// </summary>
    public class UnitFilterLike
    {
        /// <summary>
        /// Metadata information for the Unit.
        /// </summary>
        [JsonProperty("meta")]
        public UnitFilterLikeMeta? Meta { get; set; } = null;

        /// <summary>
        /// External is a reusable object that can be used to store external information about the unit from another system, used for third-party integration tracking.
        /// </summary>
        [JsonProperty("external")]
        public UnitFilterLikeExternal? External { get; set; } = null;

        /// <summary>
        /// The title of the unit.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The description of the unit.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;
    }
}