//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Requests
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Threading.Tasks;
    
    public class EmployeeSearchResponse
    {
        public Func<Task<EmployeeSearchResponse?>>? Next {get;set;}

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// Response for Employee Search operation - returns filtered Employee results
        /// </summary>
        public EmployeeSearch? EmployeeSearch { get; set; }
    }
}