//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Requests
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    
    public class StudentUpdateRequest
    {

        /// <summary>
        /// The unique identifier of the Student to update
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Request body
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public StudentUpdate StudentUpdate { get; set; } = default!;
    }
}