//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Meitner.Models.Requests
{
    using Meitner.Models.Components;
    using Meitner.Utils;
    using Newtonsoft.Json;
    
    public class StudentCreateResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// Response for Student Create operation - returns the created Student
        /// </summary>
        public Student? Student { get; set; }
    }
}