workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Directory API:
        inputs:
            - location: https://api.staging.meitner.se/directory/v1/openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/meitner-2u8/api/directory-api
targets:
    meitner:
        target: csharp
        source: Directory API
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/meitner-2u8/api/directory-api-csharp-code-samples
            labelOverride:
                fixedValue: Csharp (SDK)
            blocking: false
